name = "GPT-5.2"
release_date = "2025-12-08"
last_updated = "2025-12-08"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true

[cost]
input = 1.5909
output = 12.7273
cache_read = 0.1591

[limit]
context = 400_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
