name = "GPT-5.4-Nano"
release_date = "2026-03-11"
last_updated = "2026-03-11"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true

[cost]
input = 0.1818
output = 1.1364
cache_read = 0.0182

[limit]
context = 400_000
input = 272_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
