name = "Claude-Haiku-4.5"
family = "claude-haiku"
release_date = "2025-10-15"
last_updated = "2025-10-15"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true

[cost]
input = 0.8586
output = 4.2929
cache_read = 0.0859
cache_write = 1.0732

[limit]
context = 192_000
output = 64_000

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
