name = "Claude-Sonnet-4.5"
family = "claude-sonnet"
release_date = "2025-09-26"
last_updated = "2025-09-26"
attachment = true
reasoning = true
temperature = false
open_weights = false
tool_call = true

[cost]
input = 2.5758
output = 12.8788
cache_read = 0.2576
cache_write = 3.2197

[limit]
context = 983_040
output = 32_768

[modalities]
input = ["text", "image", "pdf"]
output = ["text"]
